engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
    exclude_paths:
    - "spec/"
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-48
