require: rubocop-rspec

AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'spec/demo/**/*'
    - 'spec/support/**/*'
    - 'vendor/**/*'
    - '*.gemspec'
  TargetRubyVersion: 2.4

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Max: 15

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
  
