require: rubocop-rspec

AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'spec/demo/**/*'
    - 'spec/support/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false
